name: Deploy Model

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Download Model Artifact
        uses: actions/download-artifact@v4
        with:
          name: trained-model
          path: models/

      - name: List Model Files
        run: |
          echo "Models available:"
          ls models/

      - name: Download Report Artifact
        uses: actions/download-artifact@v4
        with:
          name: training-report
          path: .

      - name: Show Report
        run: |
          echo "Training Report:"
          cat report.md

      - name: Encrypt and Upload Model Files
        env:
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME || 'default_username' }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          SERVER_URL: ${{ secrets.SERVER_URL }}
        run: |
          python scripts/encrypt_and_upload.py upload models/
